-- turtle-tools 1.0
local t=turtle
local function usage() print("Turtle Tools 1.0"); print("status | inventory | fuel | refuel [count] | move <forward|back|up|down> [count] | turn <left|right> [count] | inspect [front|up|down] | detect [front|up|down] | compare [front|up|down] | dig [front|up|down] [count] | place [front|up|down] | attack [front|up|down] | select <1-16> | count [slot] | space [slot] | transfer <slot> [count] | compact | suck [front|up|down] [count] | drop [front|up|down] [count] | craft [limit] | equip <left|right> | mine <count> --yes") end
local function num(v,d) local x=tonumber(v); return x and math.floor(x) or d end
local function slot(v) local x=num(v,0); if x<1 or x>16 then print("Slot must be 1-16."); return nil end; return x end
local function ok(a,b) if a then return true end print("Failed: "..tostring(b or "operation failed")); return false end
local function detail(s) return t.getItemDetail(s,true) end
local function item(d) return d and (d.displayName or d.name or "unknown") or "(empty)" end
local function fuel() print("Fuel: "..tostring(t.getFuelLevel()).."/"..tostring(t.getFuelLimit())) end
local function upgrades() print("Left:  "..item(t.getEquippedLeft())); print("Right: "..item(t.getEquippedRight())) end
local function status() print("=== Turtle Status ==="); fuel(); print("Selected slot: "..t.getSelectedSlot()); upgrades(); print("Modem: "..(peripheral.find("modem") and "available" or "none")) end
local function inv() local used,total=0,0; for s=1,16 do local c=t.getItemCount(s); if c>0 then used=used+1; total=total+c; print(("%2d  %-38s %5d"):format(s,item(detail(s)),c)) end end; print("Occupied: "..used.."/16"); print("Items: "..total) end
local function directional(dir,a,b,c) if dir=="up" then return b() elseif dir=="down" then return c() elseif not dir or dir=="front" or dir=="forward" then return a() end; print("Direction must be front, up or down."); return false end
local function inspect(dir) local a,b=directional(dir,t.inspect,t.inspectUp,t.inspectDown); if not a then print("No block: "..tostring(b or "air")); return end; print("Name: "..tostring(b.name or "unknown")); if b.state then print("State: "..textutils.serialize(b.state)) end; if b.tags then print("Tags: "..textutils.serialize(b.tags)) end end
local function detect(dir) print((dir or "front")..": "..(directional(dir,t.detect,t.detectUp,t.detectDown) and "blocked" or "clear")) end
local function compare(dir) print("Compare: "..(directional(dir,t.compare,t.compareUp,t.compareDown) and "match" or "different")) end
local function dig(dir,count) local f=(dir=="up" and t.digUp) or (dir=="down" and t.digDown) or t.dig; count=math.max(1,num(count,1)); local done=0; for i=1,count do local a=f(); if not a then break end; done=done+1 end; print("Dug: "..done) end
local function place(dir) local f=(dir=="up" and t.placeUp) or (dir=="down" and t.placeDown) or t.place; ok(f()) end
local function attack(dir) local f=(dir=="up" and t.attackUp) or (dir=="down" and t.attackDown) or t.attack; ok(f()) end
local function move(dir,count) local f={forward=t.forward,back=t.back,up=t.up,down=t.down}[dir or "forward"]; if not f then print("Direction must be forward, back, up or down."); return end; count=math.max(1,num(count,1)); for i=1,count do local a,b=f(); if not a then print("Stopped at "..i..": "..tostring(b or "blocked")); return end end; print("Moved "..count.." "..(dir or "forward")) end
local function turn(dir,count) local f=dir=="left" and t.turnLeft or dir=="right" and t.turnRight; if not f then print("Turn must be left or right."); return end; count=math.max(1,num(count,1)); for i=1,count do f() end end
local function refuel(count) local wanted=math.max(1,num(count,64)); local original=t.getSelectedSlot(); if t.refuel(wanted) then fuel(); return end; for s=1,16 do if t.getItemCount(s)>0 then t.select(s); if t.refuel(wanted) then fuel(); t.select(original); return end end end; t.select(original); print("No usable fuel found.") end
local function storage(kind,dir,count) local f;if kind=="suck" then f=(dir=="up" and t.suckUp) or (dir=="down" and t.suckDown) or t.suck else f=(dir=="up" and t.dropUp) or (dir=="down" and t.dropDown) or t.drop end; ok(f(count and math.max(1,num(count,1)) or nil)) end
local function compact() local selected=t.getSelectedSlot(); local moved=0; for a=1,16 do local da=detail(a); if da and da.name then for b=a+1,16 do local db=detail(b); if db and db.name==da.name then t.select(b); local before=t.getItemCount(b); t.transferTo(a); moved=moved+before-t.getItemCount(b) end end end end; t.select(selected); print("Moved "..moved.." item(s).") end
local function craft(limit) limit=num(limit,64); if limit<0 or limit>64 then print("Limit must be 0-64."); return end; ok(t.craft(limit)) end
local function equip(side) if side=="left" then ok(t.equipLeft()) elseif side=="right" then ok(t.equipRight()) else print("Side must be left or right.") end end
local function mine(count,yes) count=math.max(1,num(count,1)); if count>1 and not yes then print("Add --yes to confirm repeated world changes."); return end; local done=0; for i=1,count do local a,b=t.forward(); if not a then print("Stopped: "..tostring(b or "blocked")); break end; done=done+1 end; print("Moved forward: "..done) end
local c=(arg[1] or ""):lower(); if c=="" or c=="help" then usage() elseif c=="status" then status() elseif c=="inventory" or c=="inv" then inv() elseif c=="fuel" then fuel() elseif c=="refuel" then refuel(arg[2]) elseif c=="move" then move(arg[2],arg[3]) elseif c=="turn" then turn(arg[2],arg[3]) elseif c=="around" then t.turnLeft();t.turnLeft() elseif c=="inspect" then inspect(arg[2]) elseif c=="detect" then detect(arg[2]) elseif c=="compare" then compare(arg[2]) elseif c=="dig" then dig(arg[2],arg[3]) elseif c=="place" then place(arg[2]) elseif c=="attack" then attack(arg[2]) elseif c=="select" then local s=slot(arg[2]);if s then t.select(s);print("Selected "..s) end elseif c=="count" then local total=0;for s=1,16 do total=total+t.getItemCount(s) end;print("Total items: "..total) elseif c=="space" then local s=slot(arg[2] or t.getSelectedSlot());if s then print("Space: "..t.getItemSpace(s)) end elseif c=="transfer" then local s=slot(arg[2]);if s then ok(t.transferTo(s,arg[3] and math.max(1,num(arg[3],1)) or nil)) end elseif c=="compact" then compact() elseif c=="suck" then storage("suck",arg[2],arg[3]) elseif c=="drop" then storage("drop",arg[2],arg[3]) elseif c=="craft" then craft(arg[2]) elseif c=="equip" then equip(arg[2]) elseif c=="mine" then local yes=false;for i=2,#arg do if arg[i]=="--yes" then yes=true end end;mine(arg[2],yes) else print("Unknown command: "..c);usage() end
